version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "prod-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-86za3wraz7uj"
s3_prefix = "prod-sam"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "logGroupName=\"director-bot-alerts\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-86za3wraz7uj"
s3_prefix = "dev-sam"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "logGroupName=\"dev-director-bot-alerts\""
image_repositories = []
